name: Secvisogram Website

# Run only on new tags
on: 
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run-script build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: app/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}